name: Deploying

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: executing remote ssh commands using ssh key
        env:
            PRIVATE_KEY: ${{ secrets.AWS_KEY }}
            HOSTNAME: ${{secrets.AWS_HOST}}
            USER_NAME: ${{secrets.AWS_USER}}
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}

              ls
              bash ./deploy.sh