name: Deploying

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        env:
            PRIVATE_KEY: ${{ secrets.AWS_KEY }}
            HOSTNAME: ${{secrets.AWS_HOST}}
            USER_NAME: ${{secrets.AWS_USER}}
      
        run: |
          ssh -i ${PRIVATE_KEY} ${USER_NAME}@${HOSTNAME}

              cd /home
              bash deploy.sh